### ISSUE TITLE
Missing `x-ms-navigationProperty: true` on single-valued navigation properties

### ISSUE THREAD

**Issue by peombwa** [microsoft/OpenAPI.NET.OData#325] opened 2022-12-28 18:13 UTC
`team` property of `microsoft.graph.group` schema is missing `x-ms-navigationProperty: true`. `x-ms-navigationProperty: true` is missing from all single-valued navigation properties.

### Assemblies affected

Version used in DevX API.

### Steps to reproduce

- Go to https://graphexplorerapi.azurewebsites.net/$openapi?tags=groups.group&title=Groups&openapiversion=3&style=Powershell&graphVersion=v1.0.
- Inspect `team` property of `microsoft.graph.group` schema:
![image](https://user-images.githubusercontent.com/7061532/209854216-82f25484-bcac-404a-b3c9-b63cf3d35041.png)

### Expected result

All navigation properties should have `x-ms-navigationProperty: true`.

### Actual result

`x-ms-navigationProperty: true` is only applied to collection navigation properties.

**Comment by peombwa** [comment] 2023-01-09 18:37
Related to #254.

**Comment by millicentachieng** [comment] 2023-01-30 17:24
@peombwa The library is not the problem, the issue is with the `AnyOfRemover` for PowerShell on DevX API during the conversion. 

The below snippet shows the output without applying the `AnyOfRemover`:
```yaml
team:
    anyOf:
        - $ref: "#/components/schemas/microsoft.graph.team"
        - type: object
          nullable: true
    description: The team associated with this group.
    x-ms-navigationProperty: true
```

**Comment by millicentachieng** [comment] 2023-01-31 16:36
@peombwa 
Will updating the `team` navigation property on DevX API to look like the below snippet work for AutoRest?
```yaml
team:
     allOf:
          - $ref: "#/components/schemas/microsoft.graph.team"
          - type: object
            description: The team associated with this group.
            x-ms-navigationProperty: true
```
cc @darrelmiller

**Comment by peombwa** [comment] 2023-02-01 02:46
Thanks for the pointer @millicentachieng! We can transfer the issue to DevX API repo.

Unfortunately, AutoREST ignores the x-ms-navigationProperty (readOnly) in an allOf. I'll open an issue for this in their repo. 

Oddly, the following representation, which goes against [OpenAPI spec](https://swagger.io/specification/#reference-object), works with AutoREST:
``` yml
team:
  $ref: "#/components/schemas/microsoft.graph.team"
  description: The team associated with this group.
  x-ms-navigationProperty: true
```

**Comment by millicentachieng** [comment] 2023-02-01 12:31
Transferred to https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1348

**Closed by millicentachieng** 2023-02-01 12:31 UTC
Labels: p0
